### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by oshanis** [AI-and-Blockchain/F23_HealthFederated#1]
Please include setup instructions in the README to guide someone to try out your project.

**Comment by sanjaychari** [comment]
Hi @oshanis,

Thanks for the feedback. We will add the setup instructions soon, once we test all components of the setup together. We have currently tested the VFL component with the transfer learning model without Blockchain and the Blockchain and VFL integration with a dummy set of weights sent by 4 clients.
The next step is to test the end-to-end Blockchain and VFL integration with the weights being sent by each VFL client instead of the dummy weights. We will test this soon.

**Comment by sanjaychari** [comment]
I added initial setup instructions for the Blockchain and VFL integration component as it is now. We will add setup instructions for the VFL component soon. We will also combine both set of instructions in our final deliverable.
